name: time_service
description: A web-service displaying server time and name.
# version: 1.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^1.6.0
  shelf: ^0.7.5

dev_dependencies:
  pedantic: ^1.9.0
